services:
  app:
    # image: spliit2:latest
    build: .
    ports:
      - 3000:3000
    env_file:
      - container.env
    depends_on:
      db:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - container.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5
